services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailer-api:
    build:
      context: ./mailer-api
    container_name: private_mailer_api
    restart: always
    env_file:
      - .env.local
    ports:
      - "${MAILER_SERVER_PORT:-3000}:3000"

volumes:
  postgres_data: