export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  events: "/events",
  eventsManagement: "/events-management",
  eventDetail: (eventId: string = ":eventId"): string => `/events/${eventId}`,
  eventCreate: "/events/new",
  roleManagement: "/roleManagement",
  permissionManagement: "/permissionManagement",
  myInscriptions: "/inscriptions/mine",
  inscriptionsAdmin: "/inscriptions/admin",
  inscriptionsReports: "/inscriptions/reports",
  scientificWorks: "/scientific-works",
  scientificWorksManagement: "/scientific-works-management",
};
