// Lista de ciudades principales de Venezuela para el dropdown de ubicaciones
export const venezuelaCities = [
  "Caracas",
  "Maracaibo",
  "Valencia",
  "Barquisimeto",
  "Maracay",
  "Ciudad Guayana",
  "Barcelona",
  "Maturín",
  "Puerto La Cruz",
  "Petare",
  "Turmero",
  "Ciudad Bolívar",
  "San Cristóbal",
  "Mérida",
  "Cabimas",
  "Cumaná",
  "San Félix",
  "Guarenas",
  "Puerto Cabello",
  "Acarigua",
  "Los Teques",
  "Punto Fijo",
  "Valera",
  "Guacara",
  "Carúpano",
  "Catia La Mar",
  "El Tigre",
  "Guatire",
  "La Victoria",
  "Ejido",
  "Cagua"
];
